#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/note?useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: 123456

#    #配置初始化时候运行sql脚本
#    schema: classpath:sql/schema.sql
#    initialization-mode: never